version: "2"

services:
  base:
    env_file:
      - mattermost.env


  app:
    extends:
      service: base
    build:
      context: app
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    ports:
      - "11080:80"
